### ISSUE TITLE
前端技术的的讨论

### ISSUE THREAD

**Issue by Eronana** [Eronana/alicia#1]
传统的后端渲染, 还是用Vue.js之类的框架?
// update:
钦定vue.js了

**Comment by q8195438** [comment]
vue 很强，就是得现学啊，现学现卖按道理来说是不受大家滋磁的。但是，既然是新oj那么。。。

**Comment by q8195438** [comment]
vue.js + ivew 感觉很优秀。

**Comment by ZAKERR** [comment]
传统的渲染很稳定些。。。vue出错了还得找半天，ejs就很棒
